image: "scalacenter/scala-docs:1.3"

variables:
  STAGING_DIR: sbt-cache/.staging
  GIT_SUBMODULE_STRATEGY: recursive
  COURSIER_CACHE: sbt-cache/coursier
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy -Dsbt.global.staging=sbt-cache/.staging"

cache:
  key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
  untracked: true
  paths:
    - "sbt-cache/.ivy.cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

stages:
  - test

test:
  script:
    - sbt exit
